/**
 * Tests for Code Generator Types
 * 
 * Validates that all interfaces and types are properly defined and usable
 */

import { describe, it, expect } from 'vitest';
import type {
  ICodeGenerator,
  IGeneratorOptions,
  IGeneratorOutput,
  IGeneratedFile,
  ITemplateProcessor,
  IFileWriter,
  IGeneratorVisitor,
  ITemplateRegistry,
  ICodeFormatter,
  IGenerationError,
  IGenerationWarning,
  TemplateHelper,
  CompiledTemplate,
  WriteResult,
  ConflictResolutionOptions,
  ConflictResolution,
  VisitorContext,
  TemplateMetadata,
  TemplateVariable,
  TemplateInfo,
  TemplateFilter,
} from './GeneratorTypes.js';

describe('GeneratorTypes', () => {
  describe('Type Definitions', () => {
    it('should have IGeneratorOptions interface properly defined', () => {
      const options: IGeneratorOptions = {
        language: 'typescript',
        compilerOptions: {
          module: 'esm',
          target: 'es2020',
          jsx: 'react',
          strict: true,
          sourceMap: true,
          declaration: true,
        },
        formatting: {
          indent: 'spaces',
          indentSize: 2,
          lineEnding: 'lf',
          quoteStyle: 'single',
          trailingComma: 'es5',
          semicolons: true,
          printWidth: 80,
        },
        fileOrganization: {
          outputDir: './output',
          preserveStructure: true,
          fileNaming: 'kebab-case',
          directoryNaming: 'kebab-case',
          createBarrelExports: true,
          groupByType: false,
        },
        templateOptions: {
          variablePrefix: '{{',
          variableSuffix: '}}',
          enableConditionals: true,
          enableLoops: true,
          helpers: {},
        },
        transformations: {
          addHeaders: true,
          headerTemplate: '/* Generated by Willow */',
          optimizeImports: true,
          sortImports: true,
          removeUnusedImports: true,
          addMissingImports: true,
        },
        errorHandling: {
          continueOnError: false,
          maxErrors: 10,
          errorLevel: 'error',
          validateBeforeGeneration: true,
        },
      };

      expect(options).toBeDefined();
      expect(options.language).toBe('typescript');
      expect(options.compilerOptions?.module).toBe('esm');
      expect(options.formatting?.indent).toBe('spaces');
      expect(options.fileOrganization?.outputDir).toBe('./output');
      expect(options.templateOptions?.variablePrefix).toBe('{{');
      expect(options.transformations?.addHeaders).toBe(true);
      expect(options.errorHandling?.continueOnError).toBe(false);
    });

    it('should have IGeneratedFile interface properly defined', () => {
      const file: IGeneratedFile = {
        path: 'components/Button.tsx',
        content: 'export const Button = () => <button>Click me</button>;',
        sourceFile: 'src/components/Button.tsx',
        metadata: {
          template: 'component',
          timestamp: new Date(),
          checksum: 'abc123',
        },
      };

      expect(file).toBeDefined();
      expect(file.path).toBe('components/Button.tsx');
      expect(file.content).toContain('Button');
      expect(file.metadata?.template).toBe('component');
    });

    it('should have IGeneratorOutput interface properly defined', () => {
      const output: IGeneratorOutput = {
        files: [],
        errors: [],
        warnings: [],
        stats: {
          totalFiles: 10,
          successCount: 9,
          failureCount: 1,
          linesGenerated: 500,
          duration: 1000,
        },
      };

      expect(output).toBeDefined();
      expect(output.stats.totalFiles).toBe(10);
      expect(output.stats.successCount).toBe(9);
      expect(output.stats.failureCount).toBe(1);
    });

    it('should have IGenerationError interface properly defined', () => {
      const error: IGenerationError = {
        code: 'INVALID_AST',
        message: 'Invalid AST node encountered',
        file: 'component.tsx',
        line: 10,
        column: 5,
        stack: 'Error stack trace',
        context: { nodeType: 'Identifier' },
      };

      expect(error).toBeDefined();
      expect(error.code).toBe('INVALID_AST');
      expect(error.line).toBe(10);
      expect(error.context?.nodeType).toBe('Identifier');
    });

    it('should have IGenerationWarning interface properly defined', () => {
      const warning: IGenerationWarning = {
        code: 'DEPRECATED_SYNTAX',
        message: 'Using deprecated syntax',
        file: 'legacy.js',
        line: 20,
        suggestion: 'Use modern syntax instead',
      };

      expect(warning).toBeDefined();
      expect(warning.code).toBe('DEPRECATED_SYNTAX');
      expect(warning.suggestion).toBe('Use modern syntax instead');
    });

    it('should have TemplateHelper type properly defined', () => {
      const helper: TemplateHelper = (value: string) => value.toUpperCase();
      
      expect(helper).toBeDefined();
      expect(helper('test')).toBe('TEST');
    });

    it('should have WriteResult interface properly defined', () => {
      const result: WriteResult = {
        path: 'output/file.ts',
        success: true,
        bytesWritten: 1024,
        backupCreated: false,
      };

      expect(result).toBeDefined();
      expect(result.success).toBe(true);
      expect(result.bytesWritten).toBe(1024);
    });

    it('should have ConflictResolutionOptions interface properly defined', () => {
      const options: ConflictResolutionOptions = {
        strategy: 'backup',
        backupDir: '.backup',
        mergeStrategy: 'ours',
        customMerge: (existing, generated) => generated,
      };

      expect(options).toBeDefined();
      expect(options.strategy).toBe('backup');
      expect(options.mergeStrategy).toBe('ours');
      expect(options.customMerge).toBeDefined();
    });

    it('should have ConflictResolution interface properly defined', () => {
      const resolution: ConflictResolution = {
        action: 'backed-up',
        content: 'merged content',
        backupPath: '.backup/file.ts.bak',
      };

      expect(resolution).toBeDefined();
      expect(resolution.action).toBe('backed-up');
      expect(resolution.backupPath).toBe('.backup/file.ts.bak');
    });

    it('should have VisitorContext interface properly defined', () => {
      const context: VisitorContext = {
        indentLevel: 2,
        parentStack: [],
        options: { language: 'typescript' },
        state: { currentClass: 'MyComponent' },
        helpers: {
          indent: () => '  ',
          dedent: () => '',
          newline: () => '\n',
          quote: (text) => `'${text}'`,
        },
      };

      expect(context).toBeDefined();
      expect(context.indentLevel).toBe(2);
      expect(context.helpers.quote('test')).toBe("'test'");
    });

    it('should have TemplateMetadata interface properly defined', () => {
      const metadata: TemplateMetadata = {
        description: 'React component template',
        category: 'component',
        tags: ['react', 'typescript'],
        variables: [
          {
            name: 'componentName',
            type: 'string',
            description: 'Component name',
            required: true,
            pattern: '^[A-Z][a-zA-Z]*$',
          },
        ],
        version: '1.0.0',
        author: 'Willow Team',
      };

      expect(metadata).toBeDefined();
      expect(metadata.category).toBe('component');
      expect(metadata.tags).toContain('react');
      expect(metadata.variables?.[0].name).toBe('componentName');
    });

    it('should have TemplateVariable interface properly defined', () => {
      const variable: TemplateVariable = {
        name: 'className',
        type: 'string',
        description: 'CSS class name',
        defaultValue: 'default-class',
        required: false,
        pattern: '^[a-z-]+$',
      };

      expect(variable).toBeDefined();
      expect(variable.type).toBe('string');
      expect(variable.defaultValue).toBe('default-class');
    });

    it('should have TemplateInfo interface properly defined', () => {
      const info: TemplateInfo = {
        name: 'react-component',
        content: 'export const {{componentName}} = () => { return <div>{{componentName}}</div>; };',
        metadata: {
          description: 'Basic React component',
          category: 'component',
        },
        registeredAt: new Date(),
      };

      expect(info).toBeDefined();
      expect(info.name).toBe('react-component');
      expect(info.content).toContain('{{componentName}}');
    });

    it('should have TemplateFilter interface properly defined', () => {
      const filter: TemplateFilter = {
        category: 'component',
        tags: ['react', 'typescript'],
        namePattern: '^react-.*',
      };

      expect(filter).toBeDefined();
      expect(filter.category).toBe('component');
      expect(filter.tags).toContain('react');
    });
  });

  describe('Interface Implementation Examples', () => {
    it('should allow implementing ICodeGenerator interface', () => {
      class MockCodeGenerator implements ICodeGenerator {
        readonly name = 'MockGenerator';
        readonly version = '1.0.0';
        readonly supportedLanguages = ['typescript', 'javascript'];

        async generateFromAST(): Promise<string> {
          return '// Generated code';
        }

        async generateFromNodes(): Promise<string> {
          return '// Generated code';
        }

        async generateFiles(): Promise<IGeneratorOutput> {
          return {
            files: [],
            errors: [],
            warnings: [],
            stats: {
              totalFiles: 0,
              successCount: 0,
              failureCount: 0,
              linesGenerated: 0,
              duration: 0,
            },
          };
        }

        async validateAST() {
          return { valid: true, errors: [] };
        }

        async transformAST(sourceFile: any) {
          return sourceFile;
        }
      }

      const generator = new MockCodeGenerator();
      expect(generator.name).toBe('MockGenerator');
      expect(generator.supportedLanguages).toContain('typescript');
    });

    it('should allow implementing ITemplateProcessor interface', () => {
      class MockTemplateProcessor implements ITemplateProcessor {
        readonly name = 'MockProcessor';
        private helpers: Record<string, TemplateHelper> = {};

        async process(template: string, variables: Record<string, any>): Promise<string> {
          let result = template;
          Object.entries(variables).forEach(([key, value]) => {
            result = result.replace(`{{${key}}}`, String(value));
          });
          return result;
        }

        async compile(template: string): Promise<CompiledTemplate> {
          return (variables) => {
            let result = template;
            Object.entries(variables).forEach(([key, value]) => {
              result = result.replace(`{{${key}}}`, String(value));
            });
            return result;
          };
        }

        registerHelper(name: string, helper: TemplateHelper): void {
          this.helpers[name] = helper;
        }

        validateTemplate(template: string) {
          const valid = template.includes('{{') && template.includes('}}');
          return { valid, errors: valid ? [] : ['No template variables found'] };
        }
      }

      const processor = new MockTemplateProcessor();
      expect(processor.name).toBe('MockProcessor');
      
      const validation = processor.validateTemplate('Hello {{name}}!');
      expect(validation.valid).toBe(true);
    });

    it('should allow implementing IFileWriter interface', () => {
      class MockFileWriter implements IFileWriter {
        readonly name = 'MockWriter';

        async writeFile(file: IGeneratedFile): Promise<WriteResult> {
          return {
            path: file.path,
            success: true,
            bytesWritten: file.content.length,
          };
        }

        async writeFiles(files: IGeneratedFile[]): Promise<WriteResult[]> {
          return Promise.all(files.map(file => this.writeFile(file)));
        }

        async fileExists(path: string): Promise<boolean> {
          return path.includes('existing');
        }

        async handleConflict(
          file: IGeneratedFile,
          existingContent: string,
          options?: ConflictResolutionOptions
        ): Promise<ConflictResolution> {
          return {
            action: options?.strategy || 'skip',
            content: file.content,
          };
        }
      }

      const writer = new MockFileWriter();
      expect(writer.name).toBe('MockWriter');
    });

    it('should allow implementing ITemplateRegistry interface', () => {
      class MockTemplateRegistry implements ITemplateRegistry {
        readonly name = 'MockRegistry';
        private templates = new Map<string, TemplateInfo>();

        register(name: string, template: string, metadata?: TemplateMetadata): void {
          this.templates.set(name, {
            name,
            content: template,
            metadata,
            registeredAt: new Date(),
          });
        }

        get(name: string): TemplateInfo | undefined {
          return this.templates.get(name);
        }

        list(filter?: TemplateFilter): TemplateInfo[] {
          let templates = Array.from(this.templates.values());
          
          if (filter?.category) {
            templates = templates.filter(t => t.metadata?.category === filter.category);
          }
          
          return templates;
        }

        remove(name: string): boolean {
          return this.templates.delete(name);
        }

        clear(): void {
          this.templates.clear();
        }
      }

      const registry = new MockTemplateRegistry();
      registry.register('test', 'template content');
      
      expect(registry.get('test')).toBeDefined();
      expect(registry.list()).toHaveLength(1);
    });

    it('should allow implementing ICodeFormatter interface', () => {
      class MockCodeFormatter implements ICodeFormatter {
        readonly name = 'MockFormatter';

        async format(code: string, options?: IGeneratorOptions['formatting']): Promise<string> {
          let formatted = code;
          
          if (options?.indent === 'spaces' && options.indentSize) {
            const indent = ' '.repeat(options.indentSize);
            formatted = formatted.split('\n').map(line => 
              line.trim() ? indent + line : line
            ).join('\n');
          }
          
          return formatted;
        }

        async check(code: string, options?: IGeneratorOptions['formatting']): Promise<{ formatted: boolean; issues?: string[] }> {
          const issues: string[] = [];
          
          if (options?.semicolons && !code.includes(';')) {
            issues.push('Missing semicolons');
          }
          
          return { formatted: issues.length === 0, issues };
        }
      }

      const formatter = new MockCodeFormatter();
      expect(formatter.name).toBe('MockFormatter');
    });
  });
});